# Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
#Create uninitialized matrix
x = torch.empty(5, 3)
print(x)

tensor([[ 1.0228e-36,  4.5594e-41,  9.9947e-37],
        [ 4.5594e-41,  1.0668e-36,  4.5594e-41],
        [-8.4168e-32,  4.5593e-41, -8.4169e-32],
        [ 4.5593e-41, -8.4169e-32,  4.5593e-41],
        [-8.4169e-32,  4.5593e-41, -8.4170e-32]])


In [3]:
#Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.2080, 0.7892, 0.0503],
        [0.9378, 0.7344, 0.1248],
        [0.8574, 0.2440, 0.7118],
        [0.2857, 0.9417, 0.2789],
        [0.5059, 0.4854, 0.6950]])


In [4]:
#Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#Construct a tensor directly from data:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0605, -1.0184,  1.5516],
        [-1.2007,  0.6930,  1.0472],
        [ 0.9786, -0.2522,  0.7854],
        [-0.7066, -1.0879,  0.3993],
        [ 1.1442,  0.5169, -0.3112]])


In [7]:
#Get its size:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.5044, -0.1553,  1.7138],
        [-0.3080,  1.1087,  1.5986],
        [ 1.1136,  0.3820,  1.7521],
        [ 0.1105, -0.5056,  0.7777],
        [ 1.4089,  0.9632, -0.2116]])


In [9]:
print(torch.add(x,y))

tensor([[ 1.5044, -0.1553,  1.7138],
        [-0.3080,  1.1087,  1.5986],
        [ 1.1136,  0.3820,  1.7521],
        [ 0.1105, -0.5056,  0.7777],
        [ 1.4089,  0.9632, -0.2116]])


In [10]:
#Providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5044, -0.1553,  1.7138],
        [-0.3080,  1.1087,  1.5986],
        [ 1.1136,  0.3820,  1.7521],
        [ 0.1105, -0.5056,  0.7777],
        [ 1.4089,  0.9632, -0.2116]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.5044, -0.1553,  1.7138],
        [-0.3080,  1.1087,  1.5986],
        [ 1.1136,  0.3820,  1.7521],
        [ 0.1105, -0.5056,  0.7777],
        [ 1.4089,  0.9632, -0.2116]])


In [12]:
print(x[:, 1])

tensor([-1.0184,  0.6930, -0.2522, -1.0879,  0.5169])


In [13]:
#Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
#If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0925])
1.092513918876648


# NumPy Bridge

In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
#See how changing the np array changed the Torch Tensor automatically
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!