In [1]:
import torch

In [2]:
class Linear(torch.nn.Module):
    def __init__(self):
        super(Linear, self).__init__()
        
        self.a = torch.rand(1, requires_grad=True)
        self.b = torch.rand(1, requires_grad=True)
        
        print("a:{}".format(self.a))
        print("b:{}".format(self.b))
        
    def forward(self, feature):
        return self.a*feature+self.b

In [29]:
feature= torch.tensor([1])
label = torch.tensor([1])

In [30]:
linear = Linear()

a:tensor([0.0222], requires_grad=True)
b:tensor([0.0577], requires_grad=True)


In [31]:
print(linear(feature))

tensor([0.0799], grad_fn=<AddBackward0>)


In [32]:
loss = torch.square(linear(feature) - label)

In [33]:
loss.backward()

In [34]:
optimizer.step()

tensor([-1.8402])


In [35]:
print(linear.b.grad)

tensor([-1.8402])
