In [2]:
import torch
from torch import nn

In [10]:
rnn = nn.LSTM(5, 20, 2)
rnn

LSTM(5, 20, num_layers=2)

In [17]:
input = torch.randn(5, 1, 5)

print(input)

tensor([[[ 1.6902, -0.0412, -0.4228,  0.8616, -0.4763]],

        [[ 0.2647, -0.2918, -0.3335,  0.6363, -0.3305]],

        [[-2.1102, -0.5206, -0.3482, -0.5564, -0.5042]],

        [[ 0.1501, -1.1012,  0.4610,  1.4705, -0.8884]],

        [[-1.1256, -0.0936, -1.3352, -0.1771, -0.0531]]])


In [12]:
h0 = torch.randn(2, 1, 20)
c0 = torch.randn(2, 1, 20)
h0

tensor([[[ 0.8138,  0.5405, -0.3188, -0.6006, -0.1023, -0.3121,  0.7333,
          -0.3477,  0.4191,  0.1512,  0.6648,  0.3988,  0.6898,  0.7031,
          -0.7913, -0.8647, -1.6066,  0.5314, -0.9233, -0.5195]],

        [[-0.2641, -0.5135, -0.4436,  0.7324, -0.9127, -2.4785,  1.1722,
           0.0248,  0.8725, -0.8485,  0.2588, -0.6477, -0.8207,  0.4860,
          -0.1146, -0.5976,  0.9290, -1.7944, -1.7656, -1.4762]]])

In [13]:
output, (hn, cn) = rnn(input, (h0, c0))

In [14]:
print(output)

tensor([[[-0.2136, -0.1170, -0.0130, -0.1880,  0.0778, -0.2556,  0.2133,
           0.0884,  0.0115, -0.2614,  0.2345,  0.0065, -0.0829, -0.5054,
          -0.0040,  0.2844,  0.2023,  0.0617, -0.0352,  0.4529]],

        [[-0.0720, -0.0347,  0.2042, -0.0749,  0.0562, -0.2873,  0.1205,
           0.0676, -0.0097, -0.1371,  0.0745, -0.0008,  0.0145, -0.1384,
          -0.0514,  0.1849,  0.1164,  0.0099, -0.1307,  0.2936]],

        [[-0.0497, -0.0046,  0.2359, -0.0147,  0.0600, -0.2549,  0.0574,
           0.0444, -0.0199, -0.0903, -0.0146,  0.0157,  0.0780,  0.0318,
          -0.0555,  0.1337,  0.0707, -0.0105, -0.1291,  0.1205]],

        [[-0.0316,  0.0262,  0.2452,  0.0190,  0.0575, -0.2363,  0.0157,
           0.0333, -0.0207, -0.0812, -0.0382,  0.0332,  0.1092,  0.0919,
          -0.0391,  0.1097,  0.0608, -0.0092, -0.1107,  0.0176]],

        [[-0.0179,  0.0623,  0.2393,  0.0325,  0.0546, -0.2205, -0.0081,
           0.0248, -0.0196, -0.0818, -0.0398,  0.0401,  0.1302,  0.0933,
  

In [15]:
print(hn)

tensor([[[-0.0218,  0.0348,  0.0092, -0.1220, -0.0397,  0.0771, -0.0462,
           0.1367, -0.0207,  0.2032,  0.1081,  0.0081,  0.0489, -0.0035,
          -0.0557,  0.0214,  0.1748, -0.1914, -0.0661,  0.0590]],

        [[-0.0179,  0.0623,  0.2393,  0.0325,  0.0546, -0.2205, -0.0081,
           0.0248, -0.0196, -0.0818, -0.0398,  0.0401,  0.1302,  0.0933,
          -0.0240,  0.1054,  0.0678, -0.0119, -0.0958, -0.0273]]],
       grad_fn=<StackBackward>)


In [16]:
print(cn)

tensor([[[-0.0426,  0.0863,  0.0246, -0.2820, -0.0729,  0.1506, -0.0937,
           0.3789, -0.0357,  0.4439,  0.2275,  0.0170,  0.1045, -0.0061,
          -0.1183,  0.0410,  0.3527, -0.4055, -0.1123,  0.0962]],

        [[-0.0364,  0.1191,  0.5241,  0.0796,  0.1053, -0.4244, -0.0187,
           0.0549, -0.0387, -0.1465, -0.0685,  0.0820,  0.2723,  0.1789,
          -0.0399,  0.1877,  0.1534, -0.0299, -0.2383, -0.0515]]],
       grad_fn=<StackBackward>)
